services:
  localstack:
    image: localstack/localstack:2026.8.3
    container_name: localstack-opentofu-lab
    network_mode: host

    environment:
      - SERVICES=s3,sqs,dynamodb,ec2
      - EC2_VM_MANAGER=docker
      - DEBUG=0
      - PERSISTENCE=1
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
      - REQUESTS_CA_BUNDLE=/etc/localstack/custom-ca/ca-bundle.crt
      - CURL_CA_BUNDLE=/etc/localstack/custom-ca/ca-bundle.crt
      - NODE_EXTRA_CA_CERTS=/etc/localstack/custom-ca/ca-bundle.crt
      - LOCALSTACK_REQUESTS_CA_BUNDLE=/etc/localstack/custom-ca/ca-bundle.crt

    volumes:
      - localstack-data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem:/etc/localstack/custom-ca/ca-bundle.crt:ro

volumes:
  localstack-data:
